[package]
name = "eth-light-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
envy = "0.4.2"
ethers = "2.0.7"
eyre = "0.6.8"
# helios = {git = "https://github.com/a16z/helios.git", tag = "0.4.1"}
helios = { path = "../../others/helios" }
log = "0.4.19"
serde = "1.0.164"
tokio = {version = "1.28.2", features = ["macros", "rt-multi-thread"]}
