[workspace]
resolver = "2"
members = ["relayer", "types", "merkle-proofs", "pallet", "storage", "client"]

[workspace.package]
authors = ["Golden Gate"]
edition = "2021"
repository = "https://github.com/ggxchain/transaction-receipt-relayer"

[workspace.dependencies]
alloy-rlp = { version = "0.3.2", features = ["derive"] }
bytes = "1.4.0"
clap = { version = "4.3", features = ["derive"] }
env_logger = "0.10.0"
envy = "0.4.2"
ethers = "2.0.7"
eyre = "0.6.8"
helios = { git = "https://github.com/a16z/helios.git", tag = "0.4.1" }
# Helios doesn't do a pub interface to the node that operates on `payload` level
helios-client = { package = "client", git = "https://github.com/a16z/helios.git", tag = "0.4.1" }
hex = "0.4"
hex-literal = "0.4.1"
keccak-hash = "0.10.0"
log = "0.4.7"
merkle-cbt = "0.3.2"
rusqlite = "0.29.0"
salvo = "0.44.1"
serde = "1.0.164"
serde_json = "1.0.97"
sha3 = "0.10.8"
signal-hook = "0.3.15"
tokio = "1.28.2"
proptest = "1.0.0"
test-strategy = "0.3.0"

[patch."https://github.com/a16z/helios.git"]
helios = { git = "https://github.com/andor0/helios.git", branch = "max-supported-logs-number-as-environ-variable" }
helios-client = { package = "client", git = "https://github.com/andor0/helios.git", branch = "max-supported-logs-number-as-environ-variable" }
