[package]
name = "types"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true

[features]
debug = []
std = ["serde/std", "serde-big-array"]

[dependencies]
alloy-rlp.workspace = true
bytes.workspace = true
keccak-hash.workspace = true
ethbloom.workspace = true
# Optional deps 
serde = { workspace = true }
serde-big-array = { workspace = true, optional = true }

[dev-dependencies]
ethers.workspace = true
proptest.workspace = true
test-strategy.workspace = true
hex-literal.workspace = true
